import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@maptiler/sdk/dist/maptiler-sdk.css";
// import * as maptilersdk from '@maptiler/sdk';
// maptilersdk.config.apiKey = process.env.NEXT_PUBLIC_MAPTILER_API_KEY as string;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
