import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import "@maptiler/sdk/dist/maptiler-sdk.css";
import Providers from "./providers";
// import * as maptilersdk from '@maptiler/sdk';
// maptilersdk.config.apiKey = process.env.NEXT_PUBLIC_MAPTILER_API_KEY as string;

const font = Kanit({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
